apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gy
  labels:
    app: mysql-pvc
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv
  storageClassName: mysql-local-storage
 # volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: gy
spec:
  storageClassName: mysql-local-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.120.16.139
    path: "/home/gaoyang/share_folder"
